# Generated by Django 4.2.9 on 2024-01-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('model', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('flagged', models.BooleanField(default=False)),
                ('remarks', models.TextField(null=True)),
                ('user_msg', models.TextField(null=True)),
                ('assist_msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='morgan.run')),
                ('character_name', models.CharField(default='Morgan', max_length=256)),
                ('greeting', models.TextField(default="Hi. I'm **Morgan**, your AI assistant for The Dawson. I can help you with things related to The Dawson on Morgan, like answering questions and providing information about the property and its operation. How can I help you?")),
                ('msgs', models.CharField(default='Morgan', max_length=30000)),
            ],
            bases=('morgan.run',),
        ),
        migrations.AddField(
            model_name='run',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.thread'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=256, null=True)),
                ('role', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('thread_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='morgan.thread')),
            ],
        ),
    ]
