# Generated by Django 4.2.9 on 2024-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfavorite',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
