# Generated by Django 4.2.9 on 2024-01-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0002_alter_chatfavorite_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='greeting',
            field=models.TextField(default="Hi. I'm **Morgan**, your AI assistant for The Dawson. I can help you with things related to The Dawson on Morgan, like answering questions and providing information about the property and its operation. My answers my be useful, but they are **not** authoritative. How can I help you?"),
        ),
    ]
