# Generated by Django 4.2.9 on 2024-01-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0004_alter_chat_greeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
