# Generated by Django 4.2.9 on 2024-01-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0005_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.thread'),
        ),
    ]
