# Generated by Django 4.2.9 on 2024-01-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0006_alter_run_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='morgan.run'),
        ),
    ]
