# Generated by Django 4.2.9 on 2024-01-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0007_remove_run_thread_thread_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('fixed', 'Fixed'), ('rejected', 'Rejected')], max_length=20)),
                ('user_txt', models.TextField()),
                ('asst_txt', models.TextField()),
                ('flag_txt', models.TextField()),
            ],
        ),
    ]
