# Generated by Django 4.2.9 on 2024-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0008_chatflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfavorite',
            name='faq',
            field=models.BooleanField(default=False),
        ),
    ]
