# Generated by Django 4.2.9 on 2024-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0009_chatfavorite_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfavorite',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
