# Generated by Django 4.2.9 on 2024-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0010_chatfavorite_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='openai_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
