# Generated by Django 4.2.9 on 2024-01-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0011_alter_assistant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
