# Generated by Django 4.2.9 on 2024-05-11 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0012_assistant_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
